name: sd
channels:
  - conda-forge
  - pytorch
  - nodefaults

dependencies:
  # Core Python and CUDA
  - python=3.10
  - cudatoolkit=11.8
  
  # Core ML Packages
  - numpy>=1.24
  - scipy>=1.11
  - pandas>=2.1
  - scikit-learn>=1.3
  - matplotlib>=3.7
  
  # System Libraries (without strict version pins)
  - ffmpeg
  - gdal>=3.6
  - geos
  - openslide
  - poppler
  - glib
  - cairo
  
  # Image Processing Libraries
  - libtiff
  - libwebp
  - libjpeg-turbo
  - lcms2
  
  # Dev Tools
  - jupyterlab>=4.0
  - ipywidgets>=8.1
  - cmake>=3.27